##Brute Force 9 * 9 Sudoku Solver

In [2]:
import numpy as np
from IPython.display import clear_output
import time
import sys
from IPython.core.debugger import Tracer
sys.setrecursionlimit(10000)
x=0

In [3]:
def createFlagBoard(board):
    #Return a board with ones and zeroes.
    # 1 == fixed, 0 == vary
    rows = board.shape[0]
    cols = board.shape[1]
    flag_board = np.zeros((rows,cols))
    
    for i in range(rows):
        for j in range(cols):
            if board[i,j] in range(1,10):
                flag_board[i,j] = 1
    
    return flag_board

def get_pos(actual_board,flag_board,pos_type,cur_pos):
    #Get the previous or next mutable position
    # P = previous, N = next
    
    max_rows = actual_board.shape[0]
    max_cols = actual_board.shape[1]
    
    cur_row = cur_pos[0]
    cur_col = cur_pos[1]
    
    if pos_type == 'P':        

        cur_col -= 1
        last_col = -1
        last_row = -1
        step = -1
        col_reset = max_cols -1
        
    elif pos_type == 'N':
        
        cur_col += 1
        last_col = max_cols
        last_row = max_rows
        step = 1
        col_reset = 0
        
    for i in xrange(cur_row,last_row,step):
        for j in xrange(cur_col,last_col,step):                
            if flag_board[i,j] == 0:
                return (i,j)                
        cur_col = col_reset
    
    #Ideally shouldn't come here
    return (-1,-1)

def canPlace(board,pos,num):
    #Returns True if no constraints violated. else false
    row = pos[0]
    col = pos[1]
    
    #Row check
    if num in board[pos[0],]:
        return False
    
    #Col check
    if num in board[:,pos[1]]:
        return False
    
    #3*3 matrix comparisions            
    #Mat 1,2,3
    if row in range(0,3):
        if col in range(0,3):
            if num in board[0:3,0:3]:
                return False
    
        elif col in range(3,6):
            if num in board[0:3,3:6]:
                return False    
    
        elif col in range(6,9):
            if num in board[0:3,6:9]:
                return False
            
    
    elif row in range(3,6):
        if col in range(0,3):
            if num in board[3:6,0:3]:
                return False
    
        elif col in range(3,6):
            if num in board[3:6,3:6]:
                return False
    
        elif col in range(6,9):
            if num in board[3:6,6:9]:
                return False
    
    elif row in range(6,9):
        if col in range(0,3):
            if num in board[6:9,0:3]:
                return False
    
        elif col in range(3,6):
            if num in board[6:9,3:6]:
                return False   
    
        elif col in range(6,9):
            if num in board[6:9,6:9]:
                return False       
            
    return True

def solve(board,flag_board,pos,num,x):
    
    x += 1
    
    if x%500 == 0:
        print x
    #clear_output()
    #print board
    
    
    if get_pos(board,flag_board,'N',pos) == (-1,-1):        
        for i in range(1,10):
            if i not in board[pos[0],]:
                board[pos[0],pos[1]] = i
                return board
    
    elif canPlace(board,pos,num) == True:
        board[pos[0],pos[1]] = num
        pos = get_pos(board,flag_board,'N',pos)
        num = 1
        
    elif num <= 8:
        num+= 1
    
    else:
        
        if num == 9:
            board[pos[0],pos[1]] = 0
        
        pos = get_pos(board,flag_board,'P',pos)
        num = board[pos[0],pos[1]]
        
        while(num == 9):
            board[pos[0],pos[1]] = 0
            pos = get_pos(board,flag_board,'P',pos)
            num = board[pos[0],pos[1]]
            
        #check here
        num += 1
        
    return solve(board,flag_board,pos,num,x)

##Create the puzzle

In [4]:
# Enter a digit b/w 1 to 9. Enter 0 if you don't know what to enter
board = np.zeros((9,9))
board[0,0] = 2
board[0,1] = 0
board[0,2] = 0
board[0,3] = 0
board[0,4] = 7
board[0,5] = 6
board[0,6] = 0
board[0,7] = 5
board[0,8] = 9
board[1,0] = 9
board[1,1] = 3
board[1,2] = 0
board[1,3] = 0
board[1,4] = 1
board[1,5] = 0
board[1,6] = 0
board[1,7] = 0
board[1,8] = 0
board[2,0] = 0
board[2,1] = 0
board[2,2] = 6
board[2,3] = 0
board[2,4] = 0
board[2,5] = 0
board[2,6] = 0
board[2,7] = 0
board[2,8] = 0
board[3,0] = 0
board[3,1] = 4
board[3,2] = 9
board[3,3] = 2
board[3,4] = 0
board[3,5] = 1
board[3,6] = 0
board[3,7] = 0
board[3,8] = 0
board[4,0] = 6
board[4,1] = 8
board[4,2] = 0
board[4,3] = 0
board[4,4] = 0
board[4,5] = 0
board[4,6] = 0
board[4,7] = 2
board[4,8] = 5
board[5,0] = 0
board[5,1] = 0
board[5,2] = 0
board[5,3] = 4
board[5,4] = 0
board[5,5] = 5
board[5,6] = 9
board[5,7] = 1
board[5,8] = 0
board[6,0] = 0
board[6,1] = 0
board[6,2] = 0
board[6,3] = 0
board[6,4] = 0
board[6,5] = 0
board[6,6] = 7
board[6,7] = 0
board[6,8] = 0
board[7,0] = 0
board[7,1] = 0
board[7,2] = 0
board[7,3] = 0
board[7,4] = 2
board[7,5] = 0
board[7,6] = 0
board[7,7] = 4
board[7,8] = 3
board[8,0] = 3
board[8,1] = 5
board[8,2] = 0
board[8,3] = 7
board[8,4] = 9
board[8,5] = 0
board[8,6] = 0
board[8,7] = 0
board[8,8] = 1
flag_board=createFlagBoard(board)
print board

[[ 2.  0.  0.  0.  7.  6.  0.  5.  9.]
 [ 9.  3.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  6.  0.  0.  0.  0.  0.  0.]
 [ 0.  4.  9.  2.  0.  1.  0.  0.  0.]
 [ 6.  8.  0.  0.  0.  0.  0.  2.  5.]
 [ 0.  0.  0.  4.  0.  5.  9.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  7.  0.  0.]
 [ 0.  0.  0.  0.  2.  0.  0.  4.  3.]
 [ 3.  5.  0.  7.  9.  0.  0.  0.  1.]]


##Solve using Rules

In [5]:
try:
    def Sudoku(board,flag_board):
        start_pos = (-1,-1)
        for i in range(board.shape[0]):
            for j in range(board.shape[1]):
                if board[i,j] == 0:
                    start_pos = (i,j)
                    break
            if start_pos != (-1,-1):
                break
        return solve(board,flag_board,start_pos,1,0)    
except :    
    traceback.print_exc(file=sys.stdout)

In [6]:
print 'Question : \n'
print board
print '\n Answer : '
Sudoku(board,flag_board)

Question : 

[[ 2.  0.  0.  0.  7.  6.  0.  5.  9.]
 [ 9.  3.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  6.  0.  0.  0.  0.  0.  0.]
 [ 0.  4.  9.  2.  0.  1.  0.  0.  0.]
 [ 6.  8.  0.  0.  0.  0.  0.  2.  5.]
 [ 0.  0.  0.  4.  0.  5.  9.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  7.  0.  0.]
 [ 0.  0.  0.  0.  2.  0.  0.  4.  3.]
 [ 3.  5.  0.  7.  9.  0.  0.  0.  1.]]

 Answer : 
500
1000
1500
2000


array([[ 2.,  1.,  4.,  3.,  7.,  6.,  8.,  5.,  9.],
       [ 9.,  3.,  5.,  8.,  1.,  2.,  6.,  7.,  4.],
       [ 8.,  7.,  6.,  5.,  4.,  9.,  1.,  3.,  2.],
       [ 5.,  4.,  9.,  2.,  6.,  1.,  3.,  8.,  7.],
       [ 6.,  8.,  1.,  9.,  3.,  7.,  4.,  2.,  5.],
       [ 7.,  2.,  3.,  4.,  8.,  5.,  9.,  1.,  6.],
       [ 4.,  6.,  2.,  1.,  5.,  3.,  7.,  9.,  8.],
       [ 1.,  9.,  7.,  6.,  2.,  8.,  5.,  4.,  3.],
       [ 3.,  5.,  8.,  7.,  9.,  4.,  2.,  6.,  1.]])

##Extract Features: